### ISSUE TITLE
Stake Witness Reward

### ISSUE THREAD

**Issue by Rishi556** [hive-engine/steemsmartcontracts#149]
Currently witness rewards are provided as liquid. A change could be made to send the reward as staked tokens. This will provide parity with Hive(native chain), as well as gives the witnesses a stake in the platform they are witnessing for.

**Comment by 4Ykw** [comment]
I agree with this.

**Comment by Rishi556** [comment]
Completed in https://github.com/hive-engine/steemsmartcontracts/pull/157.
